// ============================================================
// AGENTS.md contract generator (EXP-AGENTS-001)
// ============================================================

import fs from "fs/promises"
import type { Dirent } from "fs"
import path from "path"
import * as sdk from "../sdk/index.js"

export type AgentsContractOptions = {
  rootDir: string
  projectName?: string
  governanceVersion?: string
  check?: boolean
}

const GENERATED_START = "<!-- AGENTS.md generated content start -->"
const GENERATED_END = "<!-- AGENTS.md generated content end -->"

function formatGeneratedFooter(projectName: string, governanceVersion: string, generatedAt: string): string {
  return `
${GENERATED_START}
---

## Contract Provenance

- **Project:** ${projectName}
- **Governance version:** ${governanceVersion}
- **Generated:** ${generatedAt}
- **Command:** \`synth project AGENTS.md\`

This file is derived. Do not edit it directly. Update source fragments or the framework baseline instead.

${GENERATED_END}
`
}

async function* walk(dir: string): AsyncGenerator<string> {
  let entries: Dirent[]
  try {
    entries = await fs.readdir(dir, { withFileTypes: true })
  } catch {
    return
  }
  entries.sort((a, b) => a.name.localeCompare(b.name))
  for (const entry of entries) {
    const full = path.join(dir, entry.name)
    if (entry.isDirectory()) {
      if (entry.name === "node_modules" || entry.name === ".git" || entry.name === "dist") continue
      yield* walk(full)
    } else if (entry.isFile() && entry.name === "AGENTS.md") {
      yield full
    }
  }
}

async function loadBaseline(rootDir: string): Promise<string> {
  const rootPath = path.join(rootDir, "AGENTS.md")
  try {
    const existing = await fs.readFile(rootPath, "utf-8")
    // Strip any previously generated footer so we can regenerate it cleanly.
    const start = existing.indexOf(GENERATED_START)
    if (start >= 0) {
      return existing.slice(0, start).trimEnd()
    }
    return existing.trimEnd()
  } catch {
    return minimalBaseline().trimEnd()
  }
}

function minimalBaseline(): string {
  return `# AI Operator Contract

> This file is generated by \`synth project AGENTS.md\`. Do not edit it directly.

## Your responsibilities

- Capture human intent as a **Mission**.
- Break the Mission into **Expeditions**.
- Record every action as an **Event**.
- Let **Replay** prove the state is correct.
- Validate source-code changes with targeted tests.

## Hard constraints

- Never bypass Mission Studio.
- Never bypass Genesis.
- Never modify replay history.
- Never violate Protected Assets.
`
}

async function collectFragments(rootDir: string): Promise<Array<{ relativePath: string; content: string; fullPath: string }>> {
  const fragments: Array<{ relativePath: string; content: string; fullPath: string }> = []
  for await (const fullPath of walk(rootDir)) {
    const relative = path.relative(rootDir, fullPath)
    if (relative === "AGENTS.md") continue
    const content = await fs.readFile(fullPath, "utf-8")
    fragments.push({ relativePath: relative.replace(/\\/g, "/"), content: content.trimEnd(), fullPath })
  }
  return fragments
}

async function newestMtime(paths: string[]): Promise<number | undefined> {
  let newest: number | undefined
  for (const p of paths) {
    try {
      const stat = await fs.stat(p)
      if (typeof stat.mtimeMs === "number" && (newest === undefined || stat.mtimeMs > newest)) {
        newest = stat.mtimeMs
      }
    } catch {
      // ignore missing files
    }
  }
  return newest
}

async function readManifest(rootDir: string): Promise<{ projectName: string; governanceVersion: string }> {
  try {
    const manifestRaw = await sdk.files.readFile(sdk.paths.manifestPath(rootDir))
    const manifest = JSON.parse(manifestRaw) as Record<string, unknown>
    return {
      projectName: typeof manifest.name === "string" ? manifest.name : "Unknown Project",
      governanceVersion: typeof manifest.governanceVersion === "string" ? manifest.governanceVersion : "unknown",
    }
  } catch {
    try {
      const pkgRaw = await fs.readFile(path.join(rootDir, "package.json"), "utf-8")
      const pkg = JSON.parse(pkgRaw) as Record<string, unknown>
      return {
        projectName: typeof pkg.name === "string" ? pkg.name : "Unknown Project",
        governanceVersion: "unknown",
      }
    } catch {
      return { projectName: "Unknown Project", governanceVersion: "unknown" }
    }
  }
}

export async function generateAgentsContract(options: AgentsContractOptions): Promise<{
  content: string
  wrote: boolean
  stale: boolean
  fragmentCount: number
}> {
  const { projectName, governanceVersion } = await readManifest(options.rootDir)
  const baseline = await loadBaseline(options.rootDir)
  const fragments = await collectFragments(options.rootDir)

  const fragmentPaths = fragments.map((f) => f.fullPath)
  const fallbackPaths = [sdk.paths.manifestPath(options.rootDir), path.join(options.rootDir, "package.json")]
  const mtime = (await newestMtime(fragmentPaths)) ?? (await newestMtime(fallbackPaths))
  const generatedAt = mtime ? new Date(mtime).toISOString() : new Date().toISOString()

  let body = baseline

  if (fragments.length > 0) {
    body += "\n\n---\n\n## Additional operator contracts from repository fragments\n\n"
    for (const fragment of fragments) {
      body += `### Source: ${fragment.relativePath}\n\n${fragment.content}\n\n`
    }
  }

  body += formatGeneratedFooter(projectName, governanceVersion, generatedAt)

  let wrote = false
  let stale = false
  const outputPath = path.join(options.rootDir, "AGENTS.md")

  if (options.check) {
    try {
      const existing = await fs.readFile(outputPath, "utf-8")
      stale = existing !== body
    } catch {
      stale = true
    }
  } else {
    try {
      const existing = await fs.readFile(outputPath, "utf-8")
      stale = existing !== body
    } catch {
      stale = true
    }
    if (stale) {
      await fs.writeFile(outputPath, body, "utf-8")
      wrote = true
    }
  }

  return { content: body, wrote, stale, fragmentCount: fragments.length }
}
