// ============================================================
// CLI: AI Interaction Manifest
// ============================================================
// Produces .synth/ai/interaction-manifest.json, a machine-readable
// contract that tells any AI agent how to engage with this specific
// SYNTH repository: purpose, allowed workflows, mutation policy,
// approval boundaries, and escalation rules.
//
// Like the other .synth/ai/ files, this is a generated artifact
// derived from canonical state and the manifest. It is not source
// of truth and is regenerated by `synth ai refresh` and `synth status`.
// ============================================================

import fs from "fs/promises"
import path from "path"
import type { CanonicalState } from "../types/index.js"
import { deriveLifecyclePhase, deriveMutationPolicy, deriveRepositoryType, type LifecyclePhase, type MutationPolicy, type RepositoryType } from "./ai-metadata.js"

export type ExpectedWorkflow = {
  name: string
  trigger: string
  command: string
  requiresApproval: boolean
}

export type ProhibitedAction = {
  action: string
  reason: string
}

export type ApprovalRequirement = {
  action: string
  evidence: string[]
  escalationMessage: string
}

export type EscalationRule = {
  condition: string
  action: string
}

export type OwnershipBoundary = {
  domain: string
  scope: string
}

export type AiInteractionManifest = {
  schema: "synth-ai-interaction-manifest-v1"
  version: string
  generatedAt: string
  repositoryPurpose: string
  repositoryType: RepositoryType
  lifecyclePhase: LifecyclePhase
  mutationPolicy: MutationPolicy
  expectedWorkflows: ExpectedWorkflow[]
  prohibitedActions: ProhibitedAction[]
  approvalRequirements: ApprovalRequirement[]
  preferredInteractionPattern: string
  evidenceExpectations: string[]
  escalationRules: EscalationRule[]
  ownershipBoundaries: OwnershipBoundary[]
}

export function deriveInteractionManifest(
  state: CanonicalState,
  manifest: { name?: string; purpose?: string; governanceVersion?: string },
): AiInteractionManifest {
  const repositoryType = deriveRepositoryType(state)
  const lifecyclePhase = deriveLifecyclePhase(state)
  const mutationPolicy = deriveMutationPolicy(lifecyclePhase)
  const projectName = manifest.name || "Synth Project"
  const projectPurpose = manifest.purpose || `Governed SYNTH project: ${projectName}`

  return {
    schema: "synth-ai-interaction-manifest-v1",
    version: "1.0.0",
    generatedAt: new Date().toISOString(),
    repositoryPurpose: projectPurpose,
    repositoryType,
    lifecyclePhase,
    mutationPolicy,
    expectedWorkflows: deriveExpectedWorkflows(repositoryType, lifecyclePhase),
    prohibitedActions: deriveProhibitedActions(mutationPolicy),
    approvalRequirements: deriveApprovalRequirements(),
    preferredInteractionPattern: derivePreferredInteractionPattern(mutationPolicy),
    evidenceExpectations: [
      "Mission or Expedition draft must reference an approved charter.",
      "State mutations must be recorded as replayable events.",
      "Bootstrap or initialization requires explicit --approve.",
      "Discovery --export produces immutable, signed baselines only.",
    ],
    escalationRules: [
      { condition: "Mutation policy is READ_ONLY", action: "Stop and ask the operator for the next step." },
      { condition: "Mission status is unclear", action: "Run `synth status` and request clarification." },
      { condition: "Governance validation fails", action: "Do not mask errors; surface them and stop." },
      { condition: "No active expedition exists", action: "Propose an expedition before executing work." },
    ],
    ownershipBoundaries: [
      { domain: "Governance", scope: "Read-only unless explicitly authorized." },
      { domain: "Mission", scope: "May propose and refine; approve only when asked." },
      { domain: "Expedition", scope: "May plan and execute within an approved expedition." },
      { domain: "Implementation", scope: "Only within an active, approved expedition." },
    ],
  }
}

function deriveExpectedWorkflows(repositoryType: RepositoryType, lifecyclePhase: LifecyclePhase): ExpectedWorkflow[] {
  const workflows: ExpectedWorkflow[] = [
    { name: "Status", trigger: "Agent needs orientation", command: "synth status", requiresApproval: false },
    { name: "Govern", trigger: "Before requesting merge or completing work", command: "npm run govern", requiresApproval: false },
    { name: "Refresh AI metadata", trigger: "After state changes", command: "synth ai refresh", requiresApproval: false },
  ]

  if (lifecyclePhase === "uninitialized") {
    workflows.push({ name: "Initialize", trigger: "Project not initialized", command: "synth init --name <name>", requiresApproval: false })
  }

  if (repositoryType === "brownfield" || repositoryType === "hybrid") {
    workflows.push({ name: "Brownfield Discovery", trigger: "Existing repository", command: "synth discover [--export]", requiresApproval: false })
  }

  if (repositoryType === "greenfield" || repositoryType === "unknown") {
    workflows.push({ name: "Genesis", trigger: "Raw product intent", command: "synth first-contact start '<intent>'", requiresApproval: true })
  }

  if (lifecyclePhase === "initialized" || lifecyclePhase === "complete") {
    workflows.push({ name: "Create Mission", trigger: "No active mission", command: "synth mission create --subject <s> --purpose <p>", requiresApproval: true })
  }

  if (lifecyclePhase === "approved" || lifecyclePhase === "executing") {
    workflows.push({ name: "Plan Expedition", trigger: "Active mission exists", command: "synth expedition create --mission <id> --subject <s> --goal <g>", requiresApproval: true })
  }

  return workflows
}

function deriveProhibitedActions(mutationPolicy: MutationPolicy): ProhibitedAction[] {
  const always: ProhibitedAction[] = [
    { action: "Edit event-log.jsonl manually", reason: "Events are immutable and replayable." },
    { action: "Edit canonical-state.json directly", reason: "State is a derived projection." },
    { action: "Run mutations outside an approved expedition", reason: "All execution must be governed." },
    { action: "Bypass Mission Studio approval", reason: "Approval is the explicit transition gate." },
  ]

  if (mutationPolicy === "READ_ONLY") {
    always.push(
      { action: "Create or approve missions", reason: "Repository is in a blocked/read-only state." },
      { action: "Execute expeditions", reason: "No mutations are permitted until unblocked." },
    )
  }

  if (mutationPolicy === "PROPOSAL_ONLY") {
    always.push(
      { action: "Apply state mutations", reason: "Only proposals are allowed; await operator approval." },
    )
  }

  return always
}

function deriveApprovalRequirements(): ApprovalRequirement[] {
  return [
    {
      action: "Bootstrap a repository",
      evidence: ["Bootstrap proposal reviewed", "Operator approval via --approve"],
      escalationMessage: "Do not bootstrap without explicit operator approval.",
    },
    {
      action: "Approve a Mission draft",
      evidence: ["Draft charter reviewed", "Confidence threshold met"],
      escalationMessage: "Mission approval is an explicit operator decision.",
    },
    {
      action: "Start an Expedition",
      evidence: ["Approved mission exists", "Expedition proposal reviewed"],
      escalationMessage: "Expeditions require mission approval and operator commit.",
    },
    {
      action: "Complete an Expedition",
      evidence: ["Acceptance criteria satisfied", "Evidence attached"],
      escalationMessage: "Expedition completion must be evidenced and approved.",
    },
  ]
}

function derivePreferredInteractionPattern(mutationPolicy: MutationPolicy): string {
  if (mutationPolicy === "READ_ONLY") {
    return "Diagnose, report, and ask. Do not mutate state."
  }
  if (mutationPolicy === "PROPOSAL_ONLY") {
    return "Propose, explain, and await approval before any mutation."
  }
  return "Operate within the active expedition; record every state change as an event."
}

export async function writeAiInteractionManifest(
  synthDir: string,
  state: CanonicalState,
  manifest: { name?: string; purpose?: string; governanceVersion?: string },
): Promise<void> {
  const aiDir = path.join(synthDir, "ai")
  await fs.mkdir(aiDir, { recursive: true })

  const interactionManifest = deriveInteractionManifest(state, manifest)
  await fs.writeFile(
    path.join(aiDir, "interaction-manifest.json"),
    JSON.stringify(interactionManifest, null, 2),
    "utf-8",
  )
}
