// ============================================================
// DOCUMENTATION EXPEDITION: Projection Templates
// ============================================================
// Markdown templates for each documentation target.
// ============================================================

import type { KnowledgeGraph, Concept } from "../types.js"

function sortedConcepts(graph: KnowledgeGraph): Concept[] {
  return [...graph.concepts].sort((a, b) => a.name.localeCompare(b.name))
}

function documentSummary(graph: KnowledgeGraph): string {
  const summaries = graph.sources
    .map((s) => s.summary)
    .filter((s): s is string => !!s && s.length > 10)
  return summaries.length > 0 ? summaries[0] : "Derived documentation generated by the Synth Documentation Expedition."
}

function conceptList(graph: KnowledgeGraph, limit?: number): string {
  const concepts = sortedConcepts(graph)
  if (concepts.length === 0) return "- No concepts extracted."
  const shown = limit === undefined ? concepts : concepts.slice(0, limit)
  const lines = shown.map((c) => `- **${c.name}** — ${c.description}`)
  if (limit !== undefined && concepts.length > limit) {
    lines.push(`- *…and ${concepts.length - limit} more concepts extracted from the knowledge base.*`)
  }
  return lines.join("\n")
}

export function readmeTemplate(graph: KnowledgeGraph): string {
  return `# README

> Generated by the Synth Documentation Expedition.

## Overview

${documentSummary(graph)}

## Key Concepts

${conceptList(graph, 50)}

## Documentation Set

- [Architecture](ARCHITECTURE.md)
- [API Reference](API.md)
- [Operator Guide](OPERATOR_GUIDE.md)
- [Developer Guide](DEVELOPER_GUIDE.md)
- [Architect Guide](ARCHITECT_GUIDE.md)
- [AI Context](AI_CONTEXT.md)
`
}

function expeditionList(graph: KnowledgeGraph): string {
  const expNodes = graph.nodes.filter(
    (n) => n.metadata?.documentClass === "expedition" && n.metadata?.expeditionStatus,
  )
  if (expNodes.length === 0) return "- No expeditions found in knowledge base.\n"
  expNodes.sort((a, b) => {
    const pa = a.metadata!.expeditionPriority || "Z"
    const pb = b.metadata!.expeditionPriority || "Z"
    const order: Record<string, number> = { Critical: 0, High: 1, Medium: 2, Low: 3 }
    return (order[pa] ?? 99) - (order[pb] ?? 99)
  })
  return expNodes
    .map(
      (n) =>
        `- **[${n.label}](${n.id})** — Status: ${n.metadata!.expeditionStatus}, Priority: ${n.metadata!.expeditionPriority || "unknown"}, Program: ${n.metadata!.expeditionProgram || "unknown"}`,
    )
    .join("\n")
}

function adrList(graph: KnowledgeGraph): string {
  const adrNodes = graph.nodes.filter(
    (n) => n.metadata?.documentClass === "adr" && n.metadata?.adrStatus,
  )
  if (adrNodes.length === 0) return "- No ADRs found in knowledge base.\n"
  adrNodes.sort((a, b) => ((b.metadata?.adrDate ?? "") > (a.metadata?.adrDate ?? "") ? -1 : 1))
  return adrNodes
    .map(
      (n) =>
        `- **[${n.label}](${n.id})** — Status: ${n.metadata!.adrStatus}, Date: ${n.metadata!.adrDate || "unknown"}, Deciders: ${n.metadata!.adrDeciders || "unknown"}`,
    )
    .join("\n")
}

export function architectureTemplate(graph: KnowledgeGraph): string {
  const architectureConcepts = sortedConcepts(graph).filter(
    (c) =>
      c.name.toLowerCase().includes("gate") ||
      c.name.toLowerCase().includes("store") ||
      c.name.toLowerCase().includes("runtime") ||
      c.name.toLowerCase().includes("engine") ||
      c.name.toLowerCase().includes("layer") ||
      c.name.toLowerCase().includes("kernel"),
  )

  return `# Architecture

> Generated by the Synth Documentation Expedition.

## System Architecture

Synth is organized as a deterministic execution kernel with clear trust boundaries.

## Architectural Concepts

${
  architectureConcepts.length > 0
    ? architectureConcepts.map((c) => `- **${c.name}** — ${c.description}`).join("\n")
    : conceptList(graph)
}

## Architecture Decisions

${adrList(graph)}

## Knowledge Sources

${graph.sources
  .filter((s) => s.domain === "architecture" || s.id.includes("architecture"))
  .map((s) => `- [${s.title}](${s.id})`)
  .join("\n") || "- Derived from system state and expedition documents."}

## Trust Boundaries

- Planning (Mission Studio) is read-only.
- Execution (ExecutionGate) is the sole mutation authority.
- Adapters are isolated from the kernel.
`
}

export function apiReferenceTemplate(graph: KnowledgeGraph): string {
  const capabilityConcepts = sortedConcepts(graph).filter((c) =>
    c.name.toLowerCase().includes("capability"),
  )

  return `# API Reference

> Generated by the Synth Documentation Expedition.

## Capabilities

${
  capabilityConcepts.length > 0
    ? capabilityConcepts.map((c) => `- **${c.name}** — ${c.description}`).join("\n")
    : conceptList(graph)
}

## Events

The system event log is the source of truth for all state changes.

## Operations

- Start a planning session
- Approve a mission model
- Execute a capability
- Replay the event log
`
}

export function operatorGuideTemplate(graph: KnowledgeGraph): string {
  const operatorConcepts = sortedConcepts(graph).filter(
    (c) =>
      c.name.toLowerCase().includes("expedition") ||
      c.name.toLowerCase().includes("mission") ||
      c.name.toLowerCase().includes("operator"),
  )

  return `# Operator Guide

> Generated by the Synth Documentation Expedition.

## Working with Synth

This guide covers the operator journey from idea to done.

## Active Expeditions

${expeditionList(graph)}

## Core Operator Concepts

${
  operatorConcepts.length > 0
    ? operatorConcepts.map((c) => `- **${c.name}** — ${c.description}`).join("\n")
    : conceptList(graph)
}

## Common Workflows

1. Define a Mission.
2. Run Expeditions to discover and decide.
3. Approve the Mission Model in Mission Studio.
4. Commit to Genesis for execution.
5. Verify through Replay.
6. Regenerate documentation.
`
}

export function developerGuideTemplate(graph: KnowledgeGraph): string {
  const devConcepts = sortedConcepts(graph).filter(
    (c) =>
      c.name.toLowerCase().includes("capability") ||
      c.name.toLowerCase().includes("test") ||
      c.name.toLowerCase().includes("adapter"),
  )

  return `# Developer Guide

> Generated by the Synth Documentation Expedition.

## Building on Synth

This guide is for contributors extending Synth.

## Developer Concepts

${
  devConcepts.length > 0
    ? devConcepts.map((c) => `- **${c.name}** — ${c.description}`).join("\n")
    : conceptList(graph)
}

## Getting Started

- Run \`npm run govern\` to verify the full pipeline.
- Add new capabilities through the Capability Registry.
- Build adapters that conform to the Adapter Architecture Specification.
- Write tests before implementation.
`
}

export function architectGuideTemplate(graph: KnowledgeGraph): string {
  const archConcepts = sortedConcepts(graph).filter(
    (c) =>
      c.name.toLowerCase().includes("constitution") ||
      c.name.toLowerCase().includes("authority") ||
      c.name.toLowerCase().includes("governance") ||
      c.name.toLowerCase().includes("decision"),
  )

  return `# Architect Guide

> Generated by the Synth Documentation Expedition.

## Architectural Governance

This guide is for architects making structural decisions.

## Governance Concepts

${
  archConcepts.length > 0
    ? archConcepts.map((c) => `- **${c.name}** — ${c.description}`).join("\n")
    : conceptList(graph)
}

## Decision Process

1. Every architectural change requires an approved Expedition.
2. Declare Impact: Constitutional, Product, User Facing, Architecture Freeze, Requires ADR.
3. If constitutional, write an ADR.
4. Verify through \`npm run govern\`.
`
}

export function aiContextTemplate(graph: KnowledgeGraph): string {
  const topConcepts = sortedConcepts(graph).slice(0, 12)

  return `# AI Context

> Generated by the Synth Documentation Expedition.
> Optimized for agent consumption.

## What Synth Is

${documentSummary(graph)}

## Core Concepts

${topConcepts.map((c) => `- ${c.name}: ${c.description}`).join("\n")}

## Working Rules

- Read the Constitution and ADRs before proposing architectural changes.
- Every change must be born as an Expedition.
- Planning (Mission Studio) never mutates runtime state.
- Execution always flows through the ExecutionGate.
- The event log is the single source of truth.
`
}
